### ISSUE TITLE
Can't load icon.png

### ISSUE THREAD

**Issue by DUOLabs333** [rhnvrm/linkpage#7]
I put the icon.png in the folder `static`, but it still doesn't load if I go to `localhost:9001`

**Comment by ElDifinitivo** [comment]
Having the same issue, no custom CA's as in the other issue as well.

Everything's been saved under `/opt/linkpage`, with the icon as `/opt/linkpage/static/icon.png`, but it's never loaded when navigating to the site.

**Comment by choupaland** [comment]
you need to refer the data file from `static_files folder`

on `config.toml`
if you setup
`static_files = "/static/custom"`

so you need to change
`page_logo_url="/opt/linkpage/static/icon.png"`
to
`page_logo_url="/static/custom/icon.png"`
