### ISSUE TITLE
Can't get data from sites signed with custom CA

### ISSUE THREAD

**Issue by DUOLabs333** [rhnvrm/linkpage#8]
i self-sign all of my sites, so I can't get any data on it, as it says, "x509: certificate signed by unknown authority"

**Comment by rhnvrm** [comment]
Hey

Could you please share some details on your infra setup? 

On a preliminary search, this seems like an issue with Docker.

**Comment by DUOLabs333** [comment]
I have all my domains behind sniproxy, which acts as the virtual hosts forwarder. Sniproxy is sitting behind nginx which is what has the custom certificate signed with my custom CA (made with `mkcert`). Also, I don't use Docker for anything.

**Comment by rhnvrm** [comment]
Can you check if the server where LinkPage is running has your certificate as trusted?

**Comment by DUOLabs333** [comment]
No, I only have it trusted in the browser.

**Comment by rhnvrm** [comment]
The open graph data about websites is fetched from the server (instead of the browser), so you will need to add the certificates as trusted in the server where LinkPage is running.

**Comment by DUOLabs333** [comment]
Ah, ok. Also, one thing -- the logo does not load even if I add it in the
config file.

**Comment by rhnvrm** [comment]
Yes I saw #7, will investigate over the weekend.
